apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Z1iOVYssem6QLBlfHnR8gqSKC59lXphW,iv:G93bOuNSvFSx30xTGtNMJa5ui6v7VQtaQLMNRRfPIZ4=,tag:R1GQymBOlg5ja4RCZ7ShLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exljavuzlae8xnrdvxx3r4fxmeq8c5jc75scwvfqgks83cyyy9fqw5x5zn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVFTOG1oUXVtQ0JHL1pr
            YmhhRGkxN2oraERWMno4bG8vMTV0MC92ZEQ0CmdIVjRqUmh5QlVoM3NLanM1MkUw
            VzEybEpnV0tFc2dOYnczS0FYWTZ3NjAKLS0tIFFsL25FbTZKV1dmNGpGUnNBQUFB
            dlRSZHhsMHRNZzF3dzdrZng1UncrRmsK2pY2x2rCl35myhAFbZMucgt+S5edr3Dp
            fKJdjS0axBVUzaOwPcV0TvfbclEH9U5eK9hFm7IWwC5V1XwbjW4ffA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T21:24:38Z"
    mac: ENC[AES256_GCM,data:llN6HfENAfLZ66+pfM0/zZvgdrVo8seRr4dWfi7xMFs4WckM8k/y+rVSO1NtyY7Br+gsApFSOgRv/z74ZHhgUFlMBvUrcjP3RBJ9mDSSS530nR0NUc3yjyb3OWmAlYkR9/rLg1dGD1owpHIcVCGIy47bYEfY8h/pCPf4LPEFrvA=,iv:XEAtTqiqioBzwwXMCNwSERj3D0xX70QOcPEx/HQG02c=,tag:xI4rHhwUn8Md3T32Iad9PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
