kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bind-secondary-config
stringData:
    named.conf: ENC[AES256_GCM,data:QvjEI6RYo6aX+hTAeuCXidF4IyKjnimLqRJVpYMTBA7H5EcDSwzS9MhTk14dx+Yw81qj03cx8DKG+yOE83kdV+vIoHYVNvSANnyuJDNdGfoKHfo9VI+SPf91/jQlzV7rCnOHWl6Y5YkTvbuWjidbrXCtioajkSFE9E9KGbYUlk2fQ2grhTM8WCwmEq7n/gnbQ/1N5799etzx3K1VIFF0AIkG+BuvkkwHiS2pjt7aC5Ysh4CiKAHUT9vHWqovsM3aBd0VZ+AqY4fpFFhnclgMpsT+7QBFhk/JQnOePtsmByheGJ+LYynj+ByT8Hr/54Ef2n5MA7zoiMuU13r4NMg2CPqEQa2zcKL4KmKE+6VMyfBXSss/9r7y7XFXVyHu2v3Wml9FpiYlFP22WZKa521qPTzipkrG6BROocW93MECd+t7gfVMl0brBNaGGn2vLH6TpgWIl0XrJN3JmRsN0lzaeGWL1ddnf1YT5bezUXxCUr7IxhwH0yvdJLV+7+yyympGAFsWWP5V5kfTMujurY9ibfeIF66AYBdPbNvnml1tVrRQJNTuorlqcfNoZC8FKiJDJ008kpN+U2aAVk9smXUyohU2FuWP9kCl3kw2pEJ2rhhKzsa6NH1UzUg5bfsF3lry3dJDP7tRyeefIOf7vqzyEWlT3VoLQ5CecSVJtYOxZl4k7JQj4vcX+HSfHKgzFjM2ym6f74Wi7Z2FE5i3faQqnUB+RZ1VLOiG6n69TvE+FE5qcLiAiBesZTOHxy/hWqhenXPcNG9kH33kOEucy5espkCJUojRKdcmBk4VrV6cfOww8YKzoPVVGTCFTh1+lL58rBvmkGLRIUe/3LuGoHvINbgrBVjEBahnWekj/ywfEEWrc+Vr4IlJFpBkCKzCtByCaQQELpqDb39HEqptSUXZS/b43GtdjAjGS1SYaxtXbSYej/CYNhzGDMo/9BEdilZ45w7mJ3nTwmt+3GYXKBge2MakHJ/hOv/MDkQcztW7jzEEAD+slKwwTHK70O4g3PjkhvgFfQVjvL2CivuUOZ1iR/nkV2bol4/iqOszQcNTmCP8TqbIJZLl66Kvh+Raj8v82UjyUb8DR8m8zzM+JzODzX5GOOmJ5yRX0Q6bYZiLgqCMc9OgYrh17dYmnm3CVbdwuT7wcyqyaJFFlQlKp/jwWY5W46yOVY6RA1eAPZjDq3Fy3hT7ja+EETCHafcvfAIZNuqXewftbYRIYjrIA2aeMOhAkZ2BmcezhE5nWvyaVCGpDJ/pDG2cfP5oBuk/1EfyTDC+6x7vWFQ+Z77LyFpZLq5lq4r25ejquWUH5yVgXCfVECTgkcU/bJ5E+KlatMC99mM4a6/6MkyfvE5Sd/urqiidpLeIwPcRIccAmdiMDTgCQKUm/bjHjoQoQH2k7QgnD9WA6axG1sJjLF02f7Uvk7dzvNJcvhdiRn9LEinJBIRFvcOeJX+6q/VvdBBbwET0Dp2yrKKsvk5622OKeZcm/ROeHOgiehigE7yMI9fjhYGcYJtjFeT4YG8Bn61TEa6ybd9o/CMP47bzEs63QxMwFgeZwyykf1WfJRqQWq5S3a5+oSkQPOzZKc/Tx3666yRZu621vlc57yH3dwuhrVMcUn/Y5PJOwhkZOmMAvRV35KT7LBqS4jPgcrKrF6rbX9HQagQKKTMFnyl9EXDKbbo5wQLN7x0fP/kOW9gjVrsO2a+70f48PXQIKbBuRC09Xz0r6of6xoTY8lUAjptQmEni1lmywobrcljLnc8x0n7I0VDEFTqsOvuS0qkiRja+McUPC17Y6HN8bar3yWrKmru7pYbtycqHP06ah8OyqbUjKN9ZIQHr8kEgKsS4w+/wpbYF1tDJZPaT11zA7OIICbz+kFkeiZl2mVgbLLO51lXkiYVs3Vd/OBSQzyFBDYKilIqhsI0qgh/fFUR2yjwYyMyA8h6oD62NbM/BK6pWZLWs,iv:m5r8tD+kb6YgQTICAvWLjxAl95WYCCZxpGSTDLqDe1w=,tag:XuHNogl/OR5ESI9lUKmTTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exljavuzlae8xnrdvxx3r4fxmeq8c5jc75scwvfqgks83cyyy9fqw5x5zn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQXdRb0Y1Q2llb05PYlFR
            QXkxVytCWkRtWUZ0YkFudncrT0xOVk4rSlFvCjg2SVhZcjhvbXUza0pOWjhRV0ht
            T0p5cW9KcXVpYnhkSEYvNmZya0xFZU0KLS0tIGRUQ0hCOXZ3TWRDcjlMZDVvSnUx
            MFBsTTRtSUZBaDdwYTVOaW9RMUVsSFUK6PY36CA2ogR1Cpg13zEZ32O+g6YIHBZP
            Q2AyY4vod/23Dql1jr4lkQX5dAiSgupOH5baP6ZNg9Yn5M7hT3t+cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T23:48:39Z"
    mac: ENC[AES256_GCM,data:nTQ64vdSHTeVvT5FYOyLhnyBtxwGDjj60HnQG0wPz71SCZkE5O6t4ocdhfe1+tITS3gtZ718F+735BKPOBqMoA9mEKzNRO0kyTnt1RL6kKsd1qk+9ZXdH3eO35E11JVhNJXBPg0aMuCoGZNYy0armK9vrj5+cYDzMkvYJVZt9rM=,iv:PJwmrGm+lNj4EAADALt3jkPAplb8TiVa4OsfK4UlBH8=,tag:JrR+GVufeOybAjeEbPuxqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
