apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Jh3as32VjA319S1Y/qCz5PjfkGMjNP0WzhwpfsGkGHWAKap1GbPoTg==,iv:eHh7MSI+Fh1jdsoBFuDZdlFnfyHv4JKCugZE/0MHI7k=,tag:2fsnTQGbng5ooa+t4eyiug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exljavuzlae8xnrdvxx3r4fxmeq8c5jc75scwvfqgks83cyyy9fqw5x5zn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQk5MYmV1WnR0bTh6ZjV6
            Y1JjSCtRSTJZbTdFMzRBTFdIOEVtV0pzRGx3CkltOUt1enY1a3NuL0xsYXFNVVpy
            U3pEd3g0N2YrUzU5NzExU3lTSmNCR2sKLS0tIDZDSzBpRzNGeEFGNE90YUpobGFD
            VzlJdWFJQnN3VmtxRjg3cXFJT0o0N2MK8gexCRkmoB+qo3WmayVv0x6eGdqfldki
            GqjfZM+4w6MtZl0buimSkhougKdMniUWJVaKdk3A9ihu2PuCvqi+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T21:24:39Z"
    mac: ENC[AES256_GCM,data:nafIpp/Pif5aB7vJp2MKjZiXl39HxEGOtWiLICII0Wf2f6Lw9Rf2/3HA4aNpuucPK9zF9PAGrz09DW7XFpvUmwRbWbL2RLXONcJ0CEDvnIfHMwb1XF6qO824sAE0k/vPe5SCuEj639Lk6FP4gSQhO2Se5OblHZRfEhw9gxlVkGI=,iv:VNf1MQunV+vBcPXOMyM/GY8jzdl/9SKJGrjU3aFrFFw=,tag:oecbIrG5k3lMj85DfTh0NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
