# Set up docker registry mirrors using harbor. Most requests will be remapped by
# the harbor webhook; this should catch the rest, e.g. containers downloaded by
# drone, which freaks out when container images start with harbor.dom.ain.
k3s_registries:
    mirrors:
        docker.io:
            endpoint:
                - ENC[AES256_GCM,data:Ej4PrBjXlfdaqzIZyx2isC7x2dDhDaPWzVezWgoTEU0C14FR0KxtQA==,iv:SCUa1omTVkvq34wPPqQAoUIG1x6X2hdJHXW0PxXLSKg=,tag:MacSlY8tLC6cWremU33vZw==,type:str]
        gcr.io:
            endpoint:
                - ENC[AES256_GCM,data:+JCsJrQyrxeIASlRpg99IKnJrSmIMBa8KGBfpjpVObw6l5kX1g==,iv:0LHKnC6Mj/7iLixaJJc/YtQwhr1WK0ZYF3HXRmjInLs=,tag:ySszKUT7FMXpUy+nT03x/Q==,type:str]
        ghcr.io:
            endpoint:
                - ENC[AES256_GCM,data:eOcout59fwhHEWNaZohPZDDiz59ZiUVYxhQw0DYK4iv2ROAcP3o=,iv:TIChcbp/7+GtEecATnU1DOWpiDzxX8cnTA12RNDr0jE=,tag:N/cKESny9ji3eiEwfMrEaw==,type:str]
        public.ecr.aws:
            endpoint:
                - ENC[AES256_GCM,data:KtMRpJn7asShTo0JBYS/aL2XTbv2xQW2kqJ3pJPX0rs54HjxC4aS0gT9nsex,iv:hG3SIMuutUmMeX1VFlBni6M3/hgyASkG38E75uE9TD8=,tag:RjXTMcxwjlgdNHbG2RSGsw==,type:str]
        quay.io:
            endpoint:
                - ENC[AES256_GCM,data:CWx8YmpwhefDK05WT1qbuYib7uuz/d03mCfv0qstQqISX9xYTw0=,iv:TsIuxm7TJNNMi7miaEh9iLP9jqqYQkB9R3ad3X+LpOs=,tag:0NrK4Rz0JvpSXgNWFAo3UA==,type:str]
        registry.k8s.io:
            endpoint:
                - ENC[AES256_GCM,data:h+zFGJTvVf9ZJTfcGdOV4WBLhIa/son3eIQJZtt1OcgCst7WZyUFspMVBtHZXA==,iv:hKD8eWA3BVimKI/qHSMF5fn7t2qXOqbgbPlOsKvbL/M=,tag:uyH4o2SzV6PaAsZ8IOZzmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exljavuzlae8xnrdvxx3r4fxmeq8c5jc75scwvfqgks83cyyy9fqw5x5zn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VThZdm0ya0c1cnVVQVVs
            SWR1S0dYWnFKbHhTdGJDWEF1TWF3eXNTY3dJCk0xb2RNb2dWczlKUytVTDFna1Av
            WVNkWVBEWVZtNkJ2RS8xckdpVVFBK0EKLS0tIHNhMkNVOG1BSXNNM1JERDFiOW5I
            R3JMajNneUI4djlKU3d5Nk02T2pwWTQK/ST1ybEESOJekGVMqgiAJqAw+Vw5T+KF
            +sNPrCWoKdCdeUGepCkrBq3thl+VZnNZ3GO8OI9leUj/YJE3TmfsZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T21:16:12Z"
    mac: ENC[AES256_GCM,data:ixEVYQwP3DrhqYSHtX3AtjCvq/1xiIoOXBZ9j1NiTpyWClY0JMyzDVkG+ZlsWPo2D3zAy0OrR122UhXGzGABfcff0lzL46sN4MGahk+2fEU7kH1H8NJfvJ8icP9RDRpk9iE7oUb+sQTeGFTci1YD5nmbhSWJn36HqJj55UABJX8=,iv:OW9PGUNPzrwbwAv8dliRYAK2y4tbac3MrU/N3QSimYk=,tag:2k0Zz7L3g/Bu2Tn9IbL3ww==,type:str]
    pgp: []
    encrypted_regex: .*
    version: 3.8.1
