apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:eqLxuNMO6xWvHDbBNt476R8D0RXCCp/rWjkoS2EQflLit3PYFs9Z1g==,iv:IfeaAdfhgVx5UkHSnMEri2wiGyXpX/Dz3lz+vpNnxs8=,tag:jwem0bXL2OtoO4pmaBW1XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exljavuzlae8xnrdvxx3r4fxmeq8c5jc75scwvfqgks83cyyy9fqw5x5zn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUDlNUWR5amo5Y3UrOE1F
            ZnMycUl5bXRDNDNYQ0hrOC93Zm5Sd0lRYXpBCjVlN2xvKytuNjBPejRoaXQyb1lF
            cDd3Y2FoYmpld0NkREdVcE14TjJFeDQKLS0tIGZGNThDVnpobGorQUFpdDVuVmNj
            V3FRVzRDVFdYVlBWZG5LOXBab0dTY00KJwhDFgxDTmNFFUgZq1bqQ4gW0eWJHeYa
            xmXeIPXq4ypfaHnLZNgRv9I7t8hcLkj54huxhsvsTsKxeWvPIdjZ5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T23:45:59Z"
    mac: ENC[AES256_GCM,data:eJgWqMLKRVWqRn4tWaXe7G9wFw31npMgzc9nmpdXisQKoxIoUFBUy88tlwdnwpFXvC7iEZ2bJi5cjOGGA7REU0jfpCeVKvMdjlNWfdNBgEgSnTpPEnzXrqvfjBH2yIZcJkHMnj12qgUQ2Lh8P/xrCKWVVTEXvI4eM1mQYeHVPrg=,iv:/q74/NGAL7Nkdys6zq1G2IWfs5yxYee1z1Up8CJxKYs=,tag:O+jIY2k5LfkmF50DUHKWnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
